---
title: "R Notebook"
output: html_notebook
author: Huiqian Yu
---

lecture 6

```{r}
library(ggplot2)
library(dplyr)
mpg %>% print(n = 5)
ggplot(data = mpg) +geom_point(mapping = aes(x = displ, y = hwy,color = class))
ggplot(data = mpg) +geom_smooth(mapping = aes(x = displ, y = hwy, linetype = drv))
```

```{r}
ggplot(data = mpg, mapping = aes(x = displ, y = hwy, color = drv)) + geom_point() + geom_smooth(mapping = aes(linetype = drv))
```

```{r}
ggplot(data = mpg,mapping = aes(x = displ, y = hwy)) + geom_smooth() +geom_point( )
```
```{r}
diamonds %>% print(5)
```
```{r}
ggplot(data = diamonds) + stat_count(mapping = aes(x = cut))
ggplot(data = diamonds) + geom_bar(mapping = aes(x = cut))
```
```{r}
ggplot(data = diamonds) + stat_summary(
mapping = aes(x = cut, y = depth), 
fun.ymin = min,
fun.ymax = max,
fun.y = median
)
```
```{r}
ggplot(data = diamonds) +
geom_bar(mapping = aes(x = cut, y = ..prop.., group = 1))
```

```{r}
demo <- tribble(~cut,         ~freq,
                "Fair",        19020,
                "Good",       18050,
                "Very Good",  12082,
                "Premium",    13791,
                "Ideal",      21551)
ggplot(data = demo) +geom_bar(mapping = aes(x = cut, y = freq), stat = "identity")
```
```{r}
 ggplot(data = diamonds, mapping = aes(x = cut, fill = clarity)) + geom_bar( position = "identity")
 ggplot(data = diamonds, mapping = aes(x = cut, fill = clarity)) + geom_bar( position = "stack")
```
```{r}
 "Increasing engine size is related to decreasing fuel economy." %>% stringr::str_wrap(width = 40) %>%
writeLines()
```
```{r}
ggplot(mpg, aes(displ, hwy)) + geom_point(aes(color = class))
ggplot(mpg, aes(displ, hwy)) + geom_point(aes(color = class))+scale_x_continuous()+scale_y_continuous() + scale_color_discrete()
```
```{r}
presidential %>% print(5)
```
```{r}
 presidential %>%
mutate(id = 33 + row_number()) %>% ggplot(aes(start, id)) + geom_point() +
geom_segment(aes(xend = end, yend = id)) +
scale_x_date(NULL, breaks = presidential$start, date_labels = "'%y")
```
```{r}
ggplot(mpg, aes(displ, hwy)) +
geom_point(aes(color = class)) +
geom_smooth(se = FALSE) +
theme(legend.position = "bottom")  +
guides(color = guide_legend(nrow = 1, override.aes = list(size = 4)))
```
```{r}
 df <- data.frame(x = runif(100), y = runif(100),
z1 = rnorm(100), z2 = abs(rnorm(100)))
ggplot(df, aes(x, y)) + geom_point(aes(color = z2), size = 3)
ggplot(df, aes(x, y)) + geom_point(aes(color = z1), size = 3) + scale_color_gradient2()
```

```{r}
library(hexbin)
df <- tibble(x = rnorm(10000), y = rnorm(10000))
ggplot(df, aes(x, y)) + geom_hex() + coord_fixed()
ggplot(df, aes(x, y)) + geom_hex() + coord_fixed() + viridis::scale_fill_viridis()
```

```{r}
suv <- mpg %>% filter(class == "suv")
compact <- mpg %>% filter(class == "compact")
ggplot(suv, aes(displ, hwy, color = drv)) + geom_point()
ggplot(compact, aes(displ, hwy, color = drv)) + geom_point()
```


set scale limits

```{r}
x_scale <- scale_x_continuous(limits = range(mpg$displ)) 
y_scale <- scale_y_continuous(limits = range(mpg$hwy)) 
col_scale <- scale_color_discrete(limits = unique(mpg$drv))
ggplot(suv, aes(displ, hwy, color = drv)) + geom_point() + x_scale + y_scale + col_scale
ggplot(compact, aes(displ, hwy, color = drv)) + geom_point() + x_scale + y_scale + col_scale + theme_dark()
```


